language: node_js
node_js:
  - "8"
env:
  - TEST_DIR=front-end
  - TEST_DIR=back-end CXX=g++-4.8
# https://github.com/travis-ci/travis-ci/issues/4771#issuecomment-241439984
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: cd $TEST_DIR && npm install && npm test